name: cdk8s-pull
on:
  pull_request:
    paths:
      - cdk8s/**
jobs:
  build-cdk8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: cdk8s
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: cdk8s
      - name: Test
        run: ./test.sh
        working-directory: cdk8s
      - name: Pack
        run: wing pack
        working-directory: cdk8s
