name: containers-pull
on:
  pull_request:
    paths:
      - containers/**
jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: containers
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: containers
      - name: Test
        run: |
          #!/bin/sh
          if [ -n "$CI" ]; then
            snapshot_mode="assert"
          else
            snapshot_mode="update"
          fi

          DEBUG=1 wing test
          wing test -t tf-aws -s $snapshot_mode containers.test.w
          wing test -t tf-aws -s $snapshot_mode containers-with-readiness.test.w
        working-directory: containers
      - name: Pack
        run: wing pack
        working-directory: containers
