name: ngrok-pull
on:
  pull_request:
    paths:
      - ngrok/**
    paths-ignore:
      - ngrok/package-lock.json
jobs:
  build-ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: ngrok
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: ngrok
      - name: Test
        run: wing test
        working-directory: ngrok
      - name: Pack
        run: wing pack
        working-directory: ngrok
