name: postgres-pull
on:
  pull_request:
    paths:
      - postgres/**
jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: postgres
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: postgres
      - name: Test
        run: wing test
        working-directory: postgres
      - name: Generate docs
        run: wing gen-docs
        working-directory: postgres
      - name: Pack
        run: wing pack
        working-directory: postgres
      - name: Check for missing changes
        run: git diff --exit-code || (echo 'Please run "npm install", "wing test", and
          "wing gen-docs" from ./postgres, and commit any changes to your
          branch.' && exit 1)
