name: Pull Request Lint
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches-ignore:
      - mergify/merge-queue/*
jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |-
            feat
            fix
            docs
            chore
            rfc
            revert
            bedrock
            budget
            checks
            cloudv2
            cognito
            containers
            dynamodb
            email
            eventbridge
            fifoqueue
            github
            jwt
            k8s
            lock
            messagefanout
            momento
            ngrok
            openai
            postgres
            python
            react
            redis
            sagemaker
            ses
            simtools
            slack
            sns
            tf
            tsoa
            vite
            websockets
          subjectPattern: ^[^A-Z][^:]+[^.]$
          subjectPatternError: Subject must start with a lowercase, should not include ':'
            and should not end with a period
          requireScope: false
