name: python-pull
on:
  pull_request:
    paths:
      - python/**
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: python
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: ifconfig
        run: ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: python
      - name: Test
        run: wing test
        working-directory: python
      - name: Pack
        run: wing pack
        working-directory: python
