name: websockets-release
on:
  push:
    branches:
      - main
    paths:
      - websockets/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: websockets
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Install winglang
        run: npm i -g winglang
      - name: Install dependencies
        run: npm install --include=dev
        working-directory: websockets
      - name: Test
        run: wing test
        working-directory: websockets
      - name: Pack
        run: wing pack
        working-directory: websockets
      - name: Publish
        run: npm publish --access=public --registry https://registry.npmjs.org --tag
          latest *.tgz
        working-directory: websockets
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
